name1=input()
name2=input()
name3=input()
name4=input()
name5=input()
name6=input()
name7=input()
name8=input()
print("Побежали на качели")
print(name1,",", name2,",", name3,",", name4,",")
print("Раскачали их на славу")
print(name5, ",",name6,",", name7, ".")
print("Загорал один ",name8," .")
print("Лучше б он, как ты, водил!")

